{
 "title": "Lap Time & Fuel",
 "description": "A simple dashboard with your lap times and fuel",
 "tags": [
  "ir",
  "lap_time",
  "fuel"
 ],
 "time": { "from": "2024-04-29T18:46:00.642Z", "to": "2024-04-29T19:27:43.356Z" },
 "templating": {
  "list": [
   { "name": "session_id", "label": "SessionID", "query": { "query": "label_values(session_id)" } },
   {
    "name": "sub_session_id",
    "label": "SubSessionID",
    "query": {
     "query": "label_values({session_id=\"$sub_session_id\"},subsession_id)"
    }
   },
   { "name": "client_id", "label": "Client", "query": { "query": "label_values(job)" } },
   {
    "name": "start_up_id",
    "label": "StartUpID",
    "query": {
     "query": "label_values(client_startup_identifier)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Session Elapsed Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "session_time{session_id=\"$session_id\", $sub_session_id=\"$sub_session_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lap Times",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "time: mm:ss.SSS" } },
   "targets": [
    {
     "expr": "lap_time{session_id=\"$session_id\", subsession_id=\"$sub_session_id\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fuel Lvl over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "expr": "fuel_level{session_id=\"$session_id\", subsession_id=\"$sub_session_id\"}",
     "legendFormat": "Fuel"
    }
   ]
  }
 ]
}